# .github/workflows/evaluate_model.yml

name: Model Evaluation

on:
  push:
    paths:
      - 'models/**'  # Trigger when models are modified
  pull_request:
    paths:
      - 'models/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies with uv
      run: |
        uv pip install --system -e .

    - name: Download data artifact
      uses: dawidd6/action-download-artifact@v4
      with:
        github_token: ${{ secrets.DATA_REPO_PAT }}
        workflow: prepare_data.yml
        name: data
        repo: isaachcamp/plant-trait-data-2021
        
    - name: Extract data
      run: |
        unzip data.zip
        rm data.zip

    - name: Test file read
      run: |
        echo "Trying to read file directly:"
        find data/train -name "*N*" -type f -exec basename {} \;
        find data/train -name "**" -type f -exec ls -la {} \; | cat -A

    - name: Clean filenames of special characters
      run: |
        # List files to see what we're dealing with
        echo "Files with raw listing:"
        ls -la data/train/
        
        # Find files with $ character using proper escaping
        echo "Finding files with $ character:"
        find data -type f -name "*\$*" -print || echo "No matches with escaped search"
        
        # Try alternative approach with grep
        echo "Files with $ using grep:"
        find data -type f | grep '\$' || echo "No matches with grep"
        
        # More robust approach using a loop over all files
        for file in $(find data -type f); do
          if [[ "$file" == *'$'* ]]; then
            newname="${file//\$/}"
            echo "Renaming: $file -> $newname"
            mv "$file" "$newname"
          fi
        done
        
        # Verify the files after cleaning
        echo "Files after cleaning:"
        find data -type f | sort
        find data/train -name "*" -type f -exec ls -la {} \; | cat -A
    
    - name: Discover and evaluate models
      run: |
        # Find all model files
        for model_file in models/*.py; do
          if [ -f "$model_file" ]; then
            model_name=$(basename $model_file .py)
            echo "Evaluating model: $model_name"
            python evaluation/evaluate_model.py --model_path "$model_file" --dpath "${{ github.workspace }}/data"
          fi
        done
    
    - name: Commit updated leaderboard
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update leaderboard"
        file_pattern: leaderboard/*
