# .github/workflows/evaluate_model.yml

name: Model Evaluation

on:
  push:
    paths:
      - 'models/**'  # Trigger when models are modified
  pull_request:
    paths:
      - 'models/**'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Write access to the repository contents

jobs:
  evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2 # Important to get the previous commit timestamp

    - name: List files after checkout
      run: |
        echo "--- Files after Checkout ---"
        ls -lR models

    - name: Get last commit timestamp
      id: last_commit
      run: |
        LAST_COMMIT_TIMESTAMP=$(git log -1 --format=%ct)
        echo "LAST_COMMIT_TIMESTAMP=$LAST_COMMIT_TIMESTAMP" >> $GITHUB_OUTPUT
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies with uv
      run: |
        uv pip install --system -e .

    - name: Download data artifact
      uses: dawidd6/action-download-artifact@v4
      with:
        github_token: ${{ secrets.DATA_REPO_PAT }}
        workflow: prepare_data.yml
        name: data
        repo: isaachcamp/plant-trait-data-2021
        
    - name: Extract data
      run: |
        unzip data.zip
        rm data.zip
    
    - name: Discover and evaluate models
      run: |
        # Find all model files, but ignore unchanged files

        echo "Last commit timestamp: ${{ steps.last_commit.outputs.LAST_COMMIT_TIMESTAMP }}"

        for model_file in models/*.py; do
          # Skip __init__.py and base_model.py files
          if [[ "$model_file" == *"__init__.py"* || "$model_file" == *"base_model.py"* ]]; then
            continue
          fi
          if [ -f "$model_file" ]; then
            MODEL_MODIFIED_TIMESTAMP=$(date -r "$model_file" +%s)
            echo "Checking $model_file - Modified: $MODEL_MODIFIED_TIMESTAMP, Last Commit: ${{ steps.last_commit.outputs.LAST_COMMIT_TIMESTAMP }}"
            if [[ "$MODEL_MODIFIED_TIMESTAMP" -gt "${{ steps.last_commit.outputs.LAST_COMMIT_TIMESTAMP }}" ]]; then
              model_name=$(basename $model_file .py)
              echo "Evaluating model: $model_name"
              python evaluation/evaluate_model.py --model_path "$model_file" --dpath "${{ github.workspace }}/data"
            fi
          fi
        done
    
    - name: Commit updated leaderboard
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        github_token: ${{ secrets.DATA_REPO_PAT }}
        commit_message: "Update leaderboard"
        file_pattern: leaderboard/*
