# .github/workflows/evaluate_model.yml

name: Model Evaluation

on:
  push:
    paths:
      - 'models/**'  # Trigger when models are modified
  pull_request:
    paths:
      - 'models/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Setup uv
      uses: astral-sh/setup-uv-action@v0.0.0
      
    - name: Install dependencies
      run: uv pip install --system -e .
    
    - name: Discover and evaluate models
      run: |
        # Find all model files
        for model_file in models/*.py; do
          if [ -f "$model_file" ]; then
            model_name=$(basename $model_file .py)
            echo "Evaluating model: $model_name"
            python evaluation/evaluate.py --model_name "$model_name" --model_path "$model_file"
          fi
        done
    
    - name: Commit updated leaderboard
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update leaderboard"
        file_pattern: leaderboard/*
