# .github/workflows/evaluate_model.yml

name: Model Evaluation

on:
  push:
    paths:
      - 'models/**'  # Trigger when models are modified
  pull_request:
    paths:
      - 'models/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies with uv
      run: |
        uv pip install --system -e .


    - name: Download data artifact
      uses: dawidd6/action-download-artifact@v4
      with:
        github_token: ${{ secrets.DATA_REPO_PAT }}
        workflow: prepare_data.yml
        name: data
        repo: isaachcamp/plant-trait-data-2021
        
    - name: Extract data
      run: |
        unzip data.zip
        # rm data.zip

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "List of files in current directory:"
        ls -la
        echo "List of files in extracted directory:"
        find ./data -type f | sort

    - name: Verify downloaded artifact
      run: |
        echo "Downloaded artifact size:"
        du -sh data.zip
        echo "Files in extracted artifact:"
        unzip -l data.zip

    - name: Check file permissions
      run: |
        echo "File permissions:"
        stat ./data/train/

    - name: Check exact filename case
      run: |
        echo "Files in data/train with exact case:"
        ls -la data/train/
        # Look specifically for files with "N" in the name
        find data/train -name "*N*" -type f

    - name: Test file read
      run: |
        echo "Trying to read file directly:"
        head -n 1 data/train/N.percent_train_data.csv || echo "Failed to read file"
    
    - name: Discover and evaluate models
      run: |
        # Find all model files
        for model_file in models/*.py; do
          if [ -f "$model_file" ]; then
            model_name=$(basename $model_file .py)
            echo "Evaluating model: $model_name"
            uv run evaluation/evaluate_model.py --model_path "$model_file" --dpath "${{ github.workspace }}/data"
          fi
        done
    
    - name: Commit updated leaderboard
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update leaderboard"
        file_pattern: leaderboard/*
